version: "3.7"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - ${HOST_SAVE_DIRC}:${CONTAINER_SAVE_DIRC}
    depends_on:
      - postgres
