version: "3.7"

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
#    volumes:
#    - postgres_volume:/var/lib/postgresql/data

  app:
    stdin_open: true
    user: root
    tty: true
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      # not sure why Z is needed, https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker
      - ${HOST_SAVE_DIRC}:${CONTAINER_SAVE_DIRC}:Z
    depends_on:
      - postgres

#volumes:
#  postgres_volume: