version: "3.7"

services:
  app:
    container_name: arxivist-python
    stdin_open: true  # docker run -i
    tty: true # docker run -t
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - ${HOST_SAVE_DIRC}:${CONTAINER_SAVE_DIRC}
    depends_on:
      - postgres

  postgres:
    container_name: arxivist-postgres
    image: 'postgres'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
##      - postgres:/var/lib/postgresql/data